[package]
name = "visualiserbox"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-sidecar = "2.1.0"
rand = "0.9.2"
raylib = "5.5.1"

[dependencies.uuid]
version = "1.18.0"
features = [
    "v4",
]